### ISSUE TITLE
TPEN Gloss Transcription (marginal, intralinear)

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Gallery-of-Glosses#17]

**Comment by thehabes** [comment]
The data entry page for this is 

https://glossing-dev.rerum.io/gloss-transcription.html?tpen-project=https://t-pen.org/TPEN/project/7084

The public site needs a page which text a resulting Witness ID and loads it for viewing.  See

http://localhost:8080/gloss-transcription.html?tpen-project=https://t-pen.org/TPEN/project/7084#https://devstore.rerum.io/v1/id/65046e52ee7021a5f6a454ca

**Comment by cubap** [comment]
In glossing-entries, there is a manuscript-profile.html that will be doing most of this, so you might want to wait or coordinate with @thehabes to make it happen.
