### ISSUE TITLE
Transcription Annotations class with validator, tests, and constructor

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/Gallery-of-Glosses#2]

**Comment by leandrumartin** [comment]
Might it be a good idea to rename this as a "Gloss" class for consistency with terminology? Or would that be more relevant as a separate class?

If I am correct in understanding that this is essentially a Gloss object, we should define what such an object would look like, with it including:

* All information that should be displayed to users browsing glosses
* Any information that should be searchable--currently, the public site's sidebar lists searching by tag, book, and theme

**Comment by cubap** [comment]
The use of this would be for rendering the text content of the Witness Fragments. In some cases, the fragment directly has text content without a `source` and in others the `source` is a TPEN project or text file URI that the fragment has a selector for. In the case where there is a selector, the context for the text content can also be provided.

**Comment by leandrumartin** [comment]
Tests might not be necessary--this might work better as an interface than a class, like the `Gloss` and `ProcessedGloss` interfaces in `lib/Gloss.ts`.
